## Project Goal

The goal of this project is to apply classification and clustering techniques to a heart disease dataset.

For the classification task, the objective is to predict whether a patient has heart disease based on clinical and demographic attributes. The target variable contains two classes: 0 represents the absence of heart disease, while 1 represents the presence of heart disease.

For the clustering task, the objective is to group patients based on similarities in their health characteristics and investigate the patterns and characteristics of the resulting clusters.

## Dataset Source

The Heart Disease dataset used in this project was sourced from Kaggle.

**Source:** https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

## Dataset Description:

In [ ]:
import pandas as pd

df = pd.read_csv("Raw_dataset.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

Number and data types of attributes

In [ ]:
print("Number of attributes:", df.shape[1])
print("\nData types of attributes:")
print(df.dtypes)

Number of attributes: 14

Data types of attributes:
age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

Number of objects (instances/records)

In [ ]:
print("Number of objects:", df.shape[0])

Number of objects: 1025

Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

Class Attribute and Label Distribution

In [ ]:
print("Class attribute: target")

print("\nClass values:")
print(df["target"].unique())

print("\nCount of instances for each label:")
print(df["target"].value_counts().sort_index())

Class attribute: target

Class values:
[0 1]

Count of instances for each label:
target
0    499
1    526
Name: count, dtype: int64

‏Sample of the Raw Dataset

In [ ]:
print("\nRandom sample of 5 rows:")
df.sample(5, random_state=42)

Random sample of 5 rows:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
527,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
359,53,0,2,128,216,0,0,115,0,0.0,2,0,0,1
447,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
621,48,1,0,130,256,1,0,150,1,0.0,2,2,3,0